name: tGLAD
channels:
  - pytorch
  - plotly
  - conda-forge
dependencies:
  # - python=3.8
  - jupyterlab
  - numpy
  - pytorch
  - torchvision
  - cudatoolkit #=10.2
  - matplotlib
  - plotly
  - pandas
  - networkx
  - scipy
  - scikit-learn
  - ipywidgets
  - pyvis
  - tqdm
  - ipdb

# prefix: "/home/kir0ul/miniforge3"
